# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'untitled.ui'
#
# Created by: PyQt5 UI code generator 5.6
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

# class EmittingStream(QtCore.QObject):
#     textWritten = QtCore.pyqtSignal(str)  # 定义一个发送str的信号
#     def write(self, text):
#         self.textWritten.emit(str(text))
class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(839, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.scrollArea = QtWidgets.QScrollArea(self.centralwidget)
        self.scrollArea.setGeometry(QtCore.QRect(60, 50, 311, 441))
        self.scrollArea.setWidgetResizable(True)
        self.scrollArea.setObjectName("scrollArea")
        self.scrollAreaWidgetContents = QtWidgets.QWidget()
        self.scrollAreaWidgetContents.setGeometry(QtCore.QRect(0, 0, 309, 439))
        self.scrollAreaWidgetContents.setObjectName("scrollAreaWidgetContents")
        self.textEdit_2 = QtWidgets.QTextEdit(self.scrollAreaWidgetContents)
        self.textEdit_2.setGeometry(QtCore.QRect(-7, 0, 321, 441))
        self.textEdit_2.setObjectName("textEdit_2")
        self.scrollArea.setWidget(self.scrollAreaWidgetContents)
        self.cunchulujing = QtWidgets.QLabel(self.centralwidget)
        self.cunchulujing.setGeometry(QtCore.QRect(430, 50, 81, 20))
        self.cunchulujing.setObjectName("cunchulujing")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(450, 80, 60, 16))
        self.label_2.setText("")
        self.label_2.setObjectName("label_2")
        self.wangyelianjie = QtWidgets.QLabel(self.centralwidget)
        self.wangyelianjie.setGeometry(QtCore.QRect(450, 80, 71, 20))
        self.wangyelianjie.setObjectName("wangyelianjie")
        self.getpictureurl = QtWidgets.QPushButton(self.centralwidget)
        self.getpictureurl.setGeometry(QtCore.QRect(600, 280, 131, 32))
        self.getpictureurl.setObjectName("getpictureurl")
        self.getpicture = QtWidgets.QPushButton(self.centralwidget)
        self.getpicture.setGeometry(QtCore.QRect(600, 320, 131, 32))
        self.getpicture.setObjectName("getpicture")
        self.ispicture = QtWidgets.QRadioButton(self.centralwidget)
        self.ispicture.setGeometry(QtCore.QRect(600, 210, 100, 20))
        self.ispicture.setObjectName("ispicture")
        self.notpicture = QtWidgets.QRadioButton(self.centralwidget)
        self.notpicture.setGeometry(QtCore.QRect(600, 240, 121, 20))
        self.notpicture.setObjectName("notpicture")
        self.xiaoxilan = QtWidgets.QLabel(self.centralwidget)
        self.xiaoxilan.setGeometry(QtCore.QRect(440, 360, 111, 20))
        self.xiaoxilan.setObjectName("xiaoxilan")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(450, 110, 60, 16))
        self.label_5.setText("")
        self.label_5.setObjectName("label_5")
        self.qishiyema = QtWidgets.QLabel(self.centralwidget)
        self.qishiyema.setGeometry(QtCore.QRect(450, 110, 51, 20))
        self.qishiyema.setObjectName("qishiyema")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(450, 140, 60, 16))
        self.label_7.setText("")
        self.label_7.setObjectName("label_7")
        self.jieshuyema = QtWidgets.QLabel(self.centralwidget)
        self.jieshuyema.setGeometry(QtCore.QRect(450, 140, 61, 20))
        self.jieshuyema.setObjectName("jieshuyema")
        self.filepath = QtWidgets.QLineEdit(self.centralwidget)
        self.filepath.setGeometry(QtCore.QRect(550, 50, 191, 21))
        self.filepath.setObjectName("filepath")
        self.startpage = QtWidgets.QLineEdit(self.centralwidget)
        self.startpage.setGeometry(QtCore.QRect(550, 110, 191, 21))
        self.startpage.setObjectName("startpage")
        self.endpage = QtWidgets.QLineEdit(self.centralwidget)
        self.endpage.setGeometry(QtCore.QRect(550, 140, 191, 21))
        self.endpage.setObjectName("endpage")
        self.textEdit = QtWidgets.QTextEdit(self.centralwidget)
        self.textEdit.setGeometry(QtCore.QRect(440, 398, 301, 81))
        self.textEdit.setObjectName("textEdit")
        self.comboBox = QtWidgets.QComboBox(self.centralwidget)
        self.comboBox.setGeometry(QtCore.QRect(550, 80, 104, 26))
        self.comboBox.setObjectName("comboBox")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        self.comboBox.addItem("")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 839, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)
        self.getpictureurl.clicked.connect(self.confirm)
        # sys.stdout = EmittingStream(textWritten=self.outputWritten)
        # sys.stderr = EmittingStream(textWritten=self.outputWritten)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.cunchulujing.setText(_translate("MainWindow", "文件存储路径"))
        self.wangyelianjie.setText(_translate("MainWindow", "曲谱类型"))
        self.getpictureurl.setText(_translate("MainWindow", "获取曲谱图片地址"))
        self.getpicture.setText(_translate("MainWindow", "下载曲谱图片"))
        self.ispicture.setText(_translate("MainWindow", "图片格式曲谱"))
        self.notpicture.setText(_translate("MainWindow", "pdf以及其他格式"))
        self.xiaoxilan.setText(_translate("MainWindow", "消息栏"))
        self.qishiyema.setText(_translate("MainWindow", "起始页码"))
        self.jieshuyema.setText(_translate("MainWindow", "结束页码"))
        self.comboBox.setItemText(0, _translate("MainWindow", "声乐：民歌"))
        self.comboBox.setItemText(1, _translate("MainWindow", "声乐：通俗"))
        self.comboBox.setItemText(2, _translate("MainWindow", "声乐：美声"))
        self.comboBox.setItemText(3, _translate("MainWindow", "声乐：合唱"))
        self.comboBox.setItemText(4, _translate("MainWindow", "声乐：少儿"))
        self.comboBox.setItemText(5, _translate("MainWindow", "声乐：外国"))
        self.comboBox.setItemText(6, _translate("MainWindow", "器乐：钢琴"))
        self.comboBox.setItemText(7, _translate("MainWindow", "器乐：笛箫"))
        self.comboBox.setItemText(8, _translate("MainWindow", "器乐：电子琴"))
        self.comboBox.setItemText(9, _translate("MainWindow", "器乐：葫芦丝"))
        self.comboBox.setItemText(10, _translate("MainWindow", "器乐：手风琴"))
        self.comboBox.setItemText(11, _translate("MainWindow", "器乐：胡琴谱"))
        self.comboBox.setItemText(12, _translate("MainWindow", "器乐：萨克斯"))
        self.comboBox.setItemText(13, _translate("MainWindow", "器乐：琵琶谱"))
        self.comboBox.setItemText(14, _translate("MainWindow", "器乐：长笛"))
        self.comboBox.setItemText(15, _translate("MainWindow", "器乐：扬琴"))
        self.comboBox.setItemText(16, _translate("MainWindow", "器乐：铜管"))
        self.comboBox.setItemText(17, _translate("MainWindow", "器乐：口琴"))
        self.comboBox.setItemText(18, _translate("MainWindow", "器乐：吉他"))
        self.comboBox.setItemText(19, _translate("MainWindow", "器乐：提琴"))
        self.comboBox.setItemText(20, _translate("MainWindow", "器乐：古筝古琴"))
        self.comboBox.setItemText(21, _translate("MainWindow", "器乐：其他乐谱"))
        self.comboBox.setItemText(22, _translate("MainWindow", "戏曲：京剧"))
        self.comboBox.setItemText(23, _translate("MainWindow", "戏曲：豫剧"))
        self.comboBox.setItemText(24, _translate("MainWindow", "戏曲：越剧"))
        self.comboBox.setItemText(25, _translate("MainWindow", "戏曲：评剧"))
        self.comboBox.setItemText(26, _translate("MainWindow", "戏曲：黄梅戏"))
        self.comboBox.setItemText(27, _translate("MainWindow", "戏曲：二人转"))
        self.comboBox.setItemText(28, _translate("MainWindow", "戏曲：花鼓戏谱"))
        self.comboBox.setItemText(29, _translate("MainWindow", "戏曲：其他唱谱"))
        self.comboBox.setItemText(30, _translate("MainWindow", "PDF乐谱：声乐"))
        self.comboBox.setItemText(31, _translate("MainWindow", "PDF乐谱：弦乐"))
        self.comboBox.setItemText(32, _translate("MainWindow", "PDF乐谱：钢琴"))
        self.comboBox.setItemText(33, _translate("MainWindow", "PDF乐谱：吉他"))
        self.comboBox.setItemText(34, _translate("MainWindow", "PDF乐谱：长笛"))
        self.comboBox.setItemText(35, _translate("MainWindow", "PDF乐谱：其他"))
    # 接收信号str的信号槽
    # def outputWritten(self, text):
    #     cursor = self.textEdit_2.textCursor()
    #     cursor.movePosition(QtGui.QTextCursor.End)
    #     cursor.insertText(text)
    #     self.textEdit_2.setTextCursor(cursor)
    #     self.textEdit_2.ensureCursorVisible()
    def confirm(self):
        filepath = self.filepath.text()
        qupulink = self.qupulink.text()
        startpage = self.startpage.text()
        endpage = self.endpage.text()
        if os.path.isfile(filepath):
            print("对不起，您应该选取一个目录,请重新输入")
            self.textEdit.setText("对不起，您应该选取一个目录,请重新输入")
   #         QtGui.QMessageBox.about("dddddddddddddd")
            return
        try:
            if os.path.isdir(filepath):
                print("目录存在,并将该目录作为存储目录")
                self.textEdit.setText("目录存在,并将该目录作为存储目录")
  #              QtGui.QMessageBox.about("dddddddddddddd")
            else:
                os.mkdir(filepath)
                print("目录不存在，新建目录，作为存储目录：" + filepath)
                self.textEdit.setText("目录不存在，新建目录，作为存储目录：" + filepath)
 #               QtGui.QMessageBox.about("dddddddddddddd")
                return
        except:
            print("目录名称有误，请重新输入")
            self.textEdit.setText("目录名称有误，请重新输入")
#            QtGui.QMessageBox.about("dddddddddddddd")
            return